# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Kinnaird College for Women
    url: https://www.kinnaird.edu.pk
  - name: CMS Kinnaird College for Women
    url: http://cms.kinnaird.edu.pk
  - name: Institutional Repository
    url: https://repository.kinnaird.edu.pk
  - name: Kinnaird Archives
    url: https://archives.kinnaird.edu.pk
  - name: Xibo
    url: https://xibo.kinnaird.edu.pk
    port: 80
    check: "tcp-ping"
    ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
   baseUrl: /kcw-status-page
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: KCW Network Status
  introTitle: "**KCW Status** – Live uptime monitoring powered by Upptime"
  introMessage: |
    This is the official uptime monitoring dashboard for **Kinnaird College for Women** IT services.
    It uses **real-time data** powered by GitHub Actions and GitHub Pages — no server needed.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/qadirbakhsh/kcw-status-page

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
